version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    networks:
      - api-network

networks:
  api-network:
    driver: bridge